services:
  vision:
    build: .
    shm_size: 4g
    # network `host` will expose all ports.
    network: "host"
    environment:
      VISION_HTTP_SERVER: "0.0.0.0:3030" # listen on public addr for future port exposing
    restart: unless-stopped
